artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/Aman123lug/End-to-End-Chicken-Disease-implementation/raw/main/data/Chicken-fecal-images.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

