artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/Aman123lug/Data-storage-for-all-projects/raw/main/Chicken-fecal-images.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion



prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_config: artifacts/prepare_base_model/base_model.h5
    updated_base_model_config: artifacts/prepare_base_model/base_model_updated.h5

